version: '3.8'

services:
  web:
    build: .
    image: yassine/my_django_app:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
