version: '3.8'

services:
  web:
    build: .
    image: yassine/my_django_app:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
      - db_data:/app/db.sqlite3  # Use a named volume for the database

volumes:
  db_data:
    driver: local
