# Generated by Django 5.0.6 on 2024-07-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=5, null=True),
        ),
    ]
