# Generated by Django 5.0.6 on 2024-07-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_question_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=20),
        ),
    ]
