# Generated by Django 5.0.6 on 2024-08-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0004_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
