# Generated by Django 5.0.6 on 2024-08-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0005_question_options_delete_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
