# Generated by Django 5.0.6 on 2024-07-19 21:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('1', 'Public'), ('2', 'Unlisted'), ('0', 'Private')], default='1', max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('restriction', models.CharField(choices=[('0', 'None'), ('1', 'Age restricted')], default='0', max_length=50)),
                ('interviewDate', models.DateField(default=datetime.date.today)),
                ('videoURL', models.URLField()),
                ('duration', models.DurationField()),
                ('size', models.FloatField()),
                ('mediaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_media', to='media.media')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.IntegerField(choices=[(1, 'Interviewer'), (2, 'Interviewee')])),
                ('VideoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmentNumber', models.IntegerField()),
                ('startTime', models.DurationField()),
                ('endTime', models.DurationField()),
                ('description', models.TextField()),
                ('VideoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('transcriptDate', models.DateTimeField()),
                ('transcription', models.TextField()),
                ('transcriptionLanguage', models.CharField(max_length=100)),
                ('transcriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
                ('videoSegmentID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='video.videosegment')),
            ],
        ),
    ]
