# Generated by Django 5.0.6 on 2024-05-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videoFile',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
