# Generated by Django 5.0.6 on 2024-09-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='size',
        ),
    ]
