# Generated by Django 5.0.6 on 2024-06-07 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='interviewDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='video',
            name='interviewee',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='interviewer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='restriction',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Age restricted')], default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('1', 'Public'), ('2', 'Unlisted'), ('0', 'Private')], default='1', max_length=50),
        ),
    ]
