# Generated by Django 5.0.6 on 2024-06-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_videofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='videoFile',
        ),
    ]
