# Generated by Django 5.0.6 on 2024-07-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='size',
            field=models.FloatField(null=True),
        ),
    ]
