# Generated by Django 5.0.6 on 2024-06-11 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_interviewdate_video_interviewee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='videoSegmentID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='video.videosegment'),
        ),
    ]
