# Generated by Django 5.0.6 on 2024-06-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_transcript_videosegmentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnailURL',
        ),
        migrations.AddField(
            model_name='video',
            name='location',
            field=models.CharField(default='unkown', max_length=100),
            preserve_default=False,
        ),
    ]
