# Generated by Django 5.0.6 on 2024-09-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_city_remove_video_location_video_city_monument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_image',
            field=models.ImageField(null=True, upload_to='cities/'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='monument_image',
            field=models.ImageField(null=True, upload_to='monuments/'),
        ),
    ]
