# Generated by Django 5.0.6 on 2024-09-23 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_city_city_image_alter_monument_monument_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='VideoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='video.video'),
        ),
    ]
