# Generated by Django 5.0.6 on 2024-06-24 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_remove_category_description_and_more'),
        ('video', '0004_remove_video_thumbnailurl_video_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='mediaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_media', to='media.media'),
        ),
    ]
