# Generated by Django 5.0.6 on 2024-09-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_participant_videoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='important_persons',
            field=models.ManyToManyField(related_name='videos', to='video.importantperson'),
        ),
        migrations.AddField(
            model_name='video',
            name='topics',
            field=models.ManyToManyField(related_name='videos', to='video.topic'),
        ),
    ]
