# Generated by Django 5.0.6 on 2024-06-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='interviewee',
        ),
        migrations.RemoveField(
            model_name='video',
            name='interviewer',
        ),
    ]
