# Generated by Django 5.0.6 on 2024-10-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_importantperson_topic_video_important_persons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='transcriberID',
        ),
    ]
