# Generated by Django 5.0.6 on 2024-08-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_media_media_media_title_dab88f_gin'),
        ('video', '0006_participant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['visibility'], name='video_video_visibil_04425e_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['location'], name='video_video_locatio_e3db8c_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['restriction'], name='video_video_restric_8f5ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['interviewDate'], name='video_video_intervi_1a7352_idx'),
        ),
    ]
