# Generated by Django 5.0.6 on 2024-10-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_remove_transcript_transcriberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='videoSegmentID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videosegment'),
        ),
    ]
