# Generated by Django 5.0.6 on 2024-10-15 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_transcript_videosegmentid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='transcriberID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcript',
            name='videoSegmentID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='video.videosegment'),
        ),
    ]
