# Generated by Django 5.0.6 on 2024-10-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_transcript_transcriberid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='videoSegmentID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videosegment'),
        ),
    ]
