# Generated by Django 5.0.6 on 2024-10-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_alter_transcript_videosegmentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='title',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='transcriberID',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='transcriptDate',
        ),
    ]
