# Generated by Django 5.0.6 on 2024-10-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_remove_transcript_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='content',
        ),
    ]
