# Generated by Django 5.0.6 on 2024-10-22 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
        ('video', '0012_remove_transcript_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='transcriptionLanguage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='media.originallanguage'),
        ),
    ]
