# Generated by Django 5.0.6 on 2024-10-24 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0013_alter_transcript_transcriptionlanguage"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="fullTranscript",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="VideoId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants_set",
                to="video.video",
            ),
        ),
    ]
