# Generated by Django 5.0.6 on 2024-11-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_alter_transcript_transcriptionlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='VideoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_set', to='video.video'),
        ),
    ]
