# Generated by Django 5.0.6 on 2024-10-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0014_video_fulltranscript_alter_participant_videoid"),
    ]

    operations = [
        migrations.AddField(
            model_name="videosegment",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
