# Generated by Django 5.0.6 on 2024-06-25 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.AddField(
            model_name='transcript',
            name='VideoSegment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='video.videosegment'),
            preserve_default=False,
        ),
    ]
