# Generated by Django 5.0.6 on 2024-06-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_remove_participant_email_transcript_videosegment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='VideoSegment',
            new_name='VideoSegmentID',
        ),
    ]
