# Generated by Django 5.0.6 on 2024-08-28 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='originalLanguage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.originallanguage'),
        ),
    ]
