# Generated by Django 5.0.6 on 2024-06-07 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='media',
            name='categoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.category'),
        ),
        migrations.AddField(
            model_name='media',
            name='uploaderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='mediaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media'),
        ),
        migrations.AddField(
            model_name='view',
            name='mediaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media'),
        ),
        migrations.AddField(
            model_name='view',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
