# Generated by Django 5.0.6 on 2024-06-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('1', 'Video'), ('2', 'Other')], default='1', max_length=50),
        ),
    ]
