# Generated by Django 5.0.6 on 2024-08-28 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_originallanguage_alter_media_originallanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='originalLanguage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='media.originallanguage'),
        ),
    ]
