# Generated by Django 5.0.6 on 2024-10-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="categoryID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="media.category",
            ),
        ),
    ]
