# Generated by Django 5.0.6 on 2024-07-26 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='channelID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='channel.channel'),
            preserve_default=False,
        ),
    ]
