# Generated by Django 5.0.6 on 2024-06-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='acknowledgement',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='media',
            name='rightsStatement',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='media',
            name='usageStatement',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='media',
            name='userNotes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('1', 'Video'), ('3', 'Audio'), ('2', 'Other')], default='1', max_length=50),
        ),
    ]
