# Generated by Django 5.0.6 on 2024-08-28 02:11

import django.db.models.deletion
from django.db import migrations, models

def create_original_language(apps, schema_editor):
    OriginalLanguage = apps.get_model('media', 'OriginalLanguage')
    OriginalLanguage.objects.get_or_create(language='en')

class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_media_originallanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='originalLanguage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='media.originallanguage'),
        ),
    ]
