# Generated by Django 5.0.6 on 2024-06-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_media_acknowledgement_media_rightsstatement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='media',
            name='rightsStatement',
        ),
        migrations.RemoveField(
            model_name='media',
            name='usageStatement',
        ),
        migrations.RemoveField(
            model_name='media',
            name='userNotes',
        ),
    ]
