# Generated by Django 5.0.6 on 2024-07-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('1', 'Video'), ('3', 'Audio'), ('4', 'Ebook'), ('2', 'Other')], default='1', max_length=50),
        ),
    ]
