# Generated by Django 5.0.6 on 2024-08-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_channelid'),
        ('media', '0005_alter_category_name'),
    ]

    operations = [
    ]
