# Generated by Django 5.0.6 on 2024-08-10 10:56

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_media_media_media_title_dab88f_gin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='media',
            name='media_media_title_dab88f_gin',
        ),
        migrations.AddIndex(
            model_name='media',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='media_media_title_087a60_gin'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='media_media_descrip_91a779_gin'),
        ),
    ]
