# Generated by Django 5.0.6 on 2024-07-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likeDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='uploadDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='viewDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
