# Generated by Django 5.0.6 on 2024-08-10 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_media_search_vector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='media',
            name='media_media_title_087a60_gin',
        ),
        migrations.RemoveIndex(
            model_name='media',
            name='media_media_descrip_91a779_gin',
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['title'], name='media_media_title_2b5507_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['description'], name='media_media_descrip_f621f3_idx'),
        ),
    ]
