# Generated by Django 5.0.6 on 2024-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_remove_media_media_media_title_087a60_gin_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='media',
            name='media_media_search__ae6970_gin',
        ),
        migrations.RemoveField(
            model_name='media',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='media',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
