# Generated by Django 5.0.6 on 2024-06-11 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_phone_number_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 6, 11, 14, 14, 38, 185117, tzinfo=datetime.timezone.utc)),
        ),
    ]
