# Generated by Django 5.0.6 on 2024-06-14 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 6, 14, 12, 14, 56, 389704, tzinfo=datetime.timezone.utc)),
        ),
    ]
