# Generated by Django 5.0.6 on 2024-06-23 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 6, 23, 21, 14, 22, 11745, tzinfo=datetime.timezone.utc)),
        ),
    ]
