# Generated by Django 5.0.6 on 2024-06-26 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 6, 26, 13, 37, 9, 211949, tzinfo=datetime.timezone.utc)),
        ),
    ]
