# Generated by Django 5.0.6 on 2024-07-07 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 7, 7, 22, 38, 45, 984955, tzinfo=datetime.timezone.utc)),
        ),
    ]
