# Generated by Django 5.0.6 on 2024-06-29 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 6, 29, 13, 47, 10, 813839, tzinfo=datetime.timezone.utc)),
        ),
    ]
