# Generated by Django 5.0.6 on 2024-06-30 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 6, 30, 19, 55, 5, 368846, tzinfo=datetime.timezone.utc)),
        ),
    ]
