# Generated by Django 5.0.6 on 2024-07-07 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 7, 7, 22, 39, 8, 687018, tzinfo=datetime.timezone.utc)),
        ),
    ]
