# Generated by Django 5.0.6 on 2024-06-30 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 6, 30, 21, 17, 43, 182766, tzinfo=datetime.timezone.utc)),
        ),
    ]
