# Generated by Django 5.0.6 on 2024-07-04 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 7, 4, 18, 10, 38, 456937, tzinfo=datetime.timezone.utc)),
        ),
    ]
