# Generated by Django 5.0.6 on 2024-07-05 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 7, 5, 16, 3, 36, 451423, tzinfo=datetime.timezone.utc)),
        ),
    ]
