# Generated by Django 5.0.6 on 2024-07-06 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 7, 6, 19, 23, 48, 274424, tzinfo=datetime.timezone.utc)),
        ),
    ]
