# Generated by Django 5.0.6 on 2024-07-09 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 7, 9, 14, 53, 5, 418109, tzinfo=datetime.timezone.utc)),
        ),
    ]
