# Generated by Django 5.0.6 on 2024-08-10 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 8, 10, 10, 57, 42, 730736, tzinfo=datetime.timezone.utc)),
        ),
    ]
