# Generated by Django 5.0.6 on 2024-07-09 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 7, 9, 15, 8, 50, 542191, tzinfo=datetime.timezone.utc)),
        ),
    ]
