# Generated by Django 5.0.6 on 2024-08-10 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 8, 10, 16, 10, 43, 121944, tzinfo=datetime.timezone.utc)),
        ),
    ]
