# Generated by Django 5.0.6 on 2024-08-13 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 8, 13, 13, 44, 11, 855965, tzinfo=datetime.timezone.utc)),
        ),
    ]
