# Generated by Django 5.0.6 on 2024-07-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_2fa_completed'),
        ('users', '0021_alter_user_dateofbirth'),
    ]

    operations = [
    ]
