# Generated by Django 4.2.14 on 2024-09-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('0', 'Playlist'), ('1', 'Collection'), ('2', 'Watch-later')], default='0', max_length=50)),
                ('privacy_status', models.CharField(choices=[('0', 'Public'), ('1', 'Private')], default='0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
