# Generated by Django 5.0.6 on 2024-06-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistmedia',
            name='description',
        ),
        migrations.AddField(
            model_name='playlist',
            name='privacy_status',
            field=models.CharField(choices=[('0', 'Public'), ('1', 'Private')], default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='playlist',
            name='type',
            field=models.CharField(choices=[('0', 'Playlist'), ('1', 'Collection')], default='0', max_length=50),
        ),
    ]
