# Generated by Django 5.0.6 on 2024-06-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_remove_playlistmedia_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistmedia',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_media_set', to='playlist.playlist'),
        ),
    ]
