# Generated by Django 5.0.6 on 2024-07-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_alter_playlistmedia_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='type',
            field=models.CharField(choices=[('0', 'Playlist'), ('1', 'Collection'), ('2', 'Watch-later')], default='0', max_length=50),
        ),
    ]
